---
hostname: che2as04
domain_name: tm.toppanmerrill.com

# Restrict SSH/NETCONF management sessions to the runner subnet.
vty_restrict_subnet: 10.231.172.0 0.0.0.255

# Keep RESTCONF disabled unless you explicitly need API-based automation.
enable_netconf: true
enable_restconf: false

vlans:
  - id: 555
    name: TEST-AUTOMATION
