---
hostname: che2as04
domain_name: tm.toppanmerrill.com

# Keep RESTCONF disabled unless you explicitly need API-based automation.
enable_netconf: true
enable_restconf: false

vlans:
  - id: 555
    name: TEST-AUTOMATION
